### ISSUE TITLE
Falla al arrancar 

### ISSUE THREAD

**Issue by yagui** [yagui/sphere-training#55]
Checking modules.
about to import.
Traceback (most recent call last):
  File "training.py", line 28, in <module>
    class Training():
  File "training.py", line 31, in Training
    class gVariables():
  File "training.py", line 732, in gVariables
    pavlovVars = saveVariables(1)
  File "training.py", line 626, in __init__
    eventTime1_sound = Training.gVariables.eventTime1_sound
NameError: global name 'Training' is not defined

Posiblemente sea un tema del archivo de configuracion. Probe borrando y generando uno nuevo a partir del .py.example pero no funciono

**Comment by alfredoivan** [comment]
Ya no falla al arrancar.
